### ISSUE TITLE
Music Youtube Search (get vidoes unavailable)

### ISSUE THREAD

**Issue by DolbyDev** [Walkyst/lavaplayer-fork#1]
### I searched for a song, but the results are available, but it is basically video not available

- Query: 'Words - Birdy';

- Result first 3 videoIds: fEhyx8su1EI, ckj0m0Pv0Sc, jqiONhGGCzk 

my server region US (Ohio)

any solution?

**Comment by Walkyst** [comment]
Usually when video/music not available YouTube Music search don't return `videoId` and this checked here https://github.com/Walkyst/lavaplayer-fork/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeSearchMusicProvider.java#L128

I think this issue on YouTube side and can't be fixed

**Comment by Walkyst** [comment]
Ah, this video available but region locked, then this is really YouTube issue, I just tested search query `Words - Birdy` and it not give me videos with this ID's `fEhyx8su1EI, ckj0m0Pv0Sc, jqiONhGGCzk`

**Comment by DolbyDev** [comment]
> Ah, this video available but region locked, then this is really YouTube issue, I just tested search query `Words - Birdy` and it not give me videos with this ID's `fEhyx8su1EI, ckj0m0Pv0Sc, jqiONhGGCzk`

I think the problem is not with the search because I tried the video in the US and it works, but when I play it shows unavailable, and it should be available because the region is the US right?

NOTE: my server region US.

**Comment by Walkyst** [comment]
Checked with VPN this ID `fEhyx8su1EI` and it playing as usually, then it strange, usually when video is region locked it not appear in search results and when tried to play show that it not available in your region

**Comment by DolbyDev** [comment]
I just realized that IPV6 is affected by region when getting video by id. 
Checked without IPV6 and it work.
