### ISSUE TITLE
Twitch tracks are not playing

### ISSUE THREAD

**Issue by aikaterna** [Walkyst/lavaplayer-fork#10]
Hello, I'm using your Lavaplayer fork @ 1.3.94 (haven't tested this on .95 yet) in a Lavalink.jar and playing a Twitch url seems to drop the track immediately after queueing. On Lavalink I see a play op with the track, and then a stop op occurs right after it. I've been testing this on various nodes in the EU and East US and it seems consistent across all of them so far.

**Comment by Walkyst** [comment]
Example of link that not work?

Tested https://twitch.tv/monstercat and it playing normally

**Comment by aikaterna** [comment]
Sorry for the trouble, it seems like it's working again on all of my test bots... I'm just going to blame Twitch on this one. I was testing with both a Lavalink CI jar from the dev branch (#1252) and also a Lavalink.jar built from https://github.com/Walkyst/lavalink-fork and neither were working, so I had assumed that it was lavaplayer causing the issue.
