### ISSUE TITLE
.wav file gives you an invalid audio format error

### ISSUE THREAD

**Issue by DRSchlaubi** [Walkyst/lavaplayer-fork#103]
If you try to play this audio file you get a FriendlyException saying "invalid file format": https://cdn.discordapp.com/attachments/826551507071402004/1109188624840396800/Verarscht.wav

**Comment by topi314** [comment]
idk what kind of cursed wav this is, but others work for me lol, even through the http source
example: https://www.kozco.com/tech/piano2.wav
