### ISSUE TITLE
Stream overrun

### ISSUE THREAD

**Issue by KagChi** [Walkyst/lavaplayer-fork#104]
https://github.com/Walkyst/lavaplayer-fork/assets/59391215/d6a2ef20-42ef-4518-95fb-2b749c76d1da

**Comment by KagChi** [comment]
https://github.com/Walkyst/lavaplayer-fork/commit/da9b2bede402aa0328d9aa82262dd5b3ec6cd3df this commit causing it

**Comment by Walkyst** [comment]
Without this commit it will fail to play, there is fix for native one decoder but issue is that it can't be compiled currently
