### ISSUE TITLE
Expose playlist metadata in playlist response object

### ISSUE THREAD

**Issue by Drapersniper** [Walkyst/lavaplayer-fork#106]
Exposing things such as type, url, author, artwork for sources that support it would be a really nice addition.

Lavascr already does a this for it's playlists inside the pluginInfo object but it would be nice seeing a more wide support for all sources natively.

**Comment by Walkyst** [comment]
Did you check readme? You can use custom branch for artworks

**Comment by Drapersniper** [comment]
This is explicitly for Playlists objects, not the tracks; currently, the artwork is exposed only to Tracks, I was talking to @TopiSenpai about it, and they asked me to open a tracking issue for it.

**Comment by topi314** [comment]
The idea is to extend the current `AudioPlaylist` interface with new fields like
`url`
`type` (playlist, album, top tracks, etc)
`artworkUrl`

These fields would all be nullable

this change could be done backwards compatible via `default` methods in the interface

**Comment by Walkyst** [comment]
`url` and `artworkUrl` shouldn't be a problem but not sure about `type` and it's purpose

**Comment by topi314** [comment]
sources like spotify, deezer & co don't only have playlists, but also albumns
having that metadata somewhere would be nice so you can say `Loaded Album x`, `Loaded Top Songs x` instead of `Loaded Playlist x` for everything

playlist author would also be interesting to output
