### ISSUE TITLE
Some Soundcloud tracks have length issue (0 length)

### ISSUE THREAD

**Issue by DolbyDev** [Walkyst/lavaplayer-fork#12]
It appears in soundcloud api in `duration` field 0 but in the `full_duration` field it shows the actual duration of the track. (I'm not sure that `full_duration` field appears on all tracks)
e.g.
`https://soundcloud.com/jahseh-onfroy/xxxtentacion-vice-city-prod`
`https://soundcloud.com/rojasonthebeat/look-at-me-ft-xxxtentacion`

`full_duration` field is unreliable due to the tracks that a subscription is required to listen.
e.g.
`https://soundcloud.com/pitbull/give-me-everything`
`https://soundcloud.com/harrystyles/watermelon-sugar`

I think the best solution is to get the duration from `media` field.

**Comment by Walkyst** [comment]
Okay, I will look into this later
