### ISSUE TITLE
[Feature] Unthrottle downloads by responding to the "n" parameter challenge

### ISSUE THREAD

**Issue by Deivu** [Walkyst/lavaplayer-fork#19]
I think lp didn't implement this yet, and I started to have this issue for some time now

Issue: https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-894619419
Relevant PR: https://github.com/ytdl-org/youtube-dl/pull/30184

**Comment by Walkyst** [comment]
LP don't download anything it just streaming audio, also we use currently `ANDROID` client and im pretty sure it not affected by throttling, since it providing deciphired links with all provided arguments for just playback audio

**Comment by duncte123** [comment]
Technically it is downloading the song but to memory. Seeing as a download is nothing more than streaming the contents to a file on the disk.

**Comment by Deivu** [comment]
This is the song in question that buffers on my side:
https://www.youtube.com/watch?v=CtNK1qV9WoE

I verified the same doesn't happen on other songs. eg:
https://www.youtube.com/watch?v=v5v0tUGlwYY

The reason why I think this is happening is because probably the speed is throttled

**Comment by Walkyst** [comment]
You try play this song on your home PC or on hosting?
Also how does it manifest, because I'm not experienced this issue at all

**Comment by Deivu** [comment]
> You try play this song on your home PC or on hosting? Also how does it manifest, because I'm not experienced this issue at all

The n parameter challenge is random based on what I see on the issues there. This is tested on prod server with a gigabit connection so bandwidth is rarely an issue.

**Comment by Walkyst** [comment]
Official YouTube app on android don't use any `n` parameters in videoplayback links, so I do not think that Google would like to limit Internet speed in its own application

**Comment by Walkyst** [comment]
Will be added in 1.3.98
