### ISSUE TITLE
Not all videos have thumbnails with /maxresdefault

### ISSUE THREAD

**Issue by DolbyDev** [Walkyst/lavaplayer-fork#2]
Not all videos have thumbnails with `https://i.ytimg.com/vi_webp/%s/maxresdefault.webp`

e.g. videos ids `kVpv8-5XWOI`, `qGKrc3A6HHM`, `X1Fqn9du7xo`

**Comment by Walkyst** [comment]
Yeah that's known, update to 1.3.88 version
