### ISSUE TITLE
JVM crash on moving the bot to another voice channel

### ISSUE THREAD

**Issue by bananasmoothii** [Walkyst/lavaplayer-fork#25]
Hello, since I migrated my project to Kotlin, my bot is constantly crashing when moved to another channel while playing music. The bot has permission to connect to both channels, here is the crash log: [hs_err_pid6034.log](https://github.com/Walkyst/lavaplayer-fork/files/7876673/hs_err_pid6034.log)

I'm a little bit confused because it works in Java, maybe I made something I shouldn't in Kotlin ?

My bot's repo is private but I can add someone if necessary.

**Comment by bananasmoothii** [comment]
PS: I regenerated my bot's token lol

**Comment by bananasmoothii** [comment]
UUhh I'm not able to replicate the issue anymore with voice channel moving, but it still happens randomly when changing the music very often
[hs_err_pid13325.log](https://github.com/Walkyst/lavaplayer-fork/files/7876784/hs_err_pid13325.log)

**Comment by Walkyst** [comment]
Not really sure what caused this, try Java 11 or 13
