### ISSUE TITLE
Support for Age Restricted in metadata

### ISSUE THREAD

**Issue by lifeisperfecto** [Walkyst/lavaplayer-fork#28]
As a feature request,

Is it possible for lavalplayer to return whether a given audio track is age restricted. Then we could avoid playing it and having it fail, so from the start we'd know it wouldn't work?

Thanks

**Comment by Walkyst** [comment]
Not really, LP check playability status of track and throw error if it age restricted, we can't know restricted track or not without requesting info about it

**Comment by lifeisperfecto** [comment]
Ah alright
