### ISSUE TITLE
Youtube Shorts Support

### ISSUE THREAD

**Issue by Sartharon** [Walkyst/lavaplayer-fork#30]
Youtube Shorts use the same videoID as "standard" youtube videos but a different url.
`Youtube shorts: https://www.youtube.com/shorts/videoID`
`Youtube video: https://www.youtube.com/watch?v=videoID`

Youtube Shorts are also available via the "standard" youtube video URL and the "standard" video convention (`watch?v=videoID`) by entering the Shorts videoID.

Loading a "song" via the youtube shorts URL leads to an "`Unknown file format`" exception. Loading the same song via its "standard" youtube video URL shows now issues.

Since the videoID is usuable on both URLs the shorts URL isnt really needed imo but supporting it would still improve the userfriendliness 

I dont seem to be skilled enough to figure out how to add either:
- a converter converting `shorts/videoID` to `watch?v=videoID`
- a proper route for the `/shorts/` page

**Comment by Walkyst** [comment]
Will be added in 1.3.98
