### ISSUE TITLE
editable youtubei api key

### ISSUE THREAD

**Issue by NikOverflow** [Walkyst/lavaplayer-fork#48]
please make a function for other to edit the youtubei api key :D

**Comment by Walkyst** [comment]
What the point of that?

**Comment by NikOverflow** [comment]
Well, I think it would be good for others if they could change the api key, so I wouldn't find it bad in any case

**Comment by Walkyst** [comment]
I think you don't understand from where these key, this is internal YouTube key from InnerTube API and you can't generate or paste other keys for usage with that API

**Comment by NikOverflow** [comment]
Oh I did not know that
