### ISSUE TITLE
No matches found for ytsearch

### ISSUE THREAD

**Issue by karelkryda** [Walkyst/lavaplayer-fork#49]
Hello,

7 hours and 30 minutes ago (varies by user) `ytsearch:` search stopped working. One of the users on Discord wrote: "I tried using `ytmsearch:` and it worked ...".
Lavalink returns an error `lavalink.server.player.AudioLoader : No matches found`.
Playback with links to a specific song works normally.

Is it possible that there has been some change by YoutTube?

Thanks

**Comment by Timbo925** [comment]
I think it might be this line, seems like the needed information in on index 1 not 0. Didn't manage to build the package locally yet to test.

https://github.com/Walkyst/lavaplayer-fork/blob/67bfdc4757947db61105c73628f2e4c2a7e4e992/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeSearchMusicProvider.java#L94

**Comment by karelkryda** [comment]
> I think it might be this line, seems like the needed information in on index 1 not 0. Didn't manage to build the package locally yet to test.
> 
> https://github.com/Walkyst/lavaplayer-fork/blob/67bfdc4757947db61105c73628f2e4c2a7e4e992/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeSearchMusicProvider.java#L94

The line you mentioned is for `ytmsearch`, but it will probably be related. 

I tried to simulate a POST request to the youtube API and the data was returned correctly (information about the song was given in the reply). However, it is possible that the response structure (JSON) has been modified and LavaPlayer is now parsing the data incorrectly.

**Comment by Timbo925** [comment]
Should indeed be this line to change, locally build and tested it and seems to work this way.

https://github.com/Walkyst/lavaplayer-fork/blob/67bfdc4757947db61105c73628f2e4c2a7e4e992/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeSearchProvider.java#L93

**Comment by karelkryda** [comment]
@Timbo925, so it works just fine with current LavaPlayer code?

**Comment by Timbo925** [comment]
Just had to change the index(0) to index(1) for the YoutubeSearchProvider on the line referenced above. Now its correctly extracting the song list as expected.

**Comment by topi314** [comment]
https://github.com/Walkyst/lavaplayer-fork/pull/50

**Comment by Walkyst** [comment]
Fixed in 1.3.97.1 release
