### ISSUE TITLE
Problem on youtube audio stream

### ISSUE THREAD

**Issue by SuperKali** [Walkyst/lavaplayer-fork#52]
[14:07:30] [INFO] [LocalAudioTrackExecutor]: Tried to stop track mY1IQ04tLUQ which is not playing.

**Comment by Walkyst** [comment]
What issue here? Video playing fine for me

**Comment by SuperKali** [comment]
Most of the time it seems that youtube links don't start

**Comment by Walkyst** [comment]
I think you doing something wrong with your code, if there any issue with how lp handle youtube it will throw error not info log
