### ISSUE TITLE
No result for some queries using ytsearch

### ISSUE THREAD

**Issue by Hydro001** [Walkyst/lavaplayer-fork#53]
Hi,

When using `ytsearch` with a query containing "é" or "à" or any "special" character, for exemple `Video détaillée`, i get : `No matches found` and when looking at the request it replaces "é" with "Θ" for exemple, it replaces other special characters too, so i think that the problem comes from lavaplayer not handling UTF-8 characters correctly or something like that.

Thanks.

Error :
```
2022-06-25 23:58:07.312  INFO 13696 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:Hugo DΘcrypte - Annonces de Macron dΘtaillΘes, dΘputΘs accusΘs, trΘsor α 17 milliards d'Ç... Actus du jour"
2022-06-25 23:58:07.533  INFO 13696 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : No matches found
```

**Comment by topi314** [comment]
1.3.97.1 fixes this issue

**Comment by Hydro001** [comment]
Could you explain me how to build the jar ?

**Comment by topi314** [comment]
this is lavaplayer
you just include it via gradle or maven

**Comment by Hydro001** [comment]
So i need to ask the lavalink authors to update lavaplayer in their builds right ?
Sorry for asking dumb questions by the way, i never used gradle or maven before

**Comment by Hydro001** [comment]
I saw your comment on lavalink, i'll try to update it as you said, have a nice day and sorry for disturbing 👍

**Comment by topi314** [comment]
see my ll issue comment
this can be closed as it's already fixed in lp
