### ISSUE TITLE
not hear audio while switching channel region.

### ISSUE THREAD

**Issue by DolbyDev** [Walkyst/lavaplayer-fork#6]
not hear audio while switching channel region to the `US East` and `US Central` Only.

When I pause and unpause the track. audio back

Is this related to lavaplayer or koe?

**Comment by Walkyst** [comment]
Not related to lavaplayer

**Comment by DolbyDev** [comment]
> Not related to lavaplayer

Do you have any knowledge of how to solve this problem or the cause of the problem?

**Comment by Walkyst** [comment]
No, sorry, i do what you said in first comment, pause and unpause player then audio back, there's maybe something with koe, not really know

**Comment by DolbyDev** [comment]
> No, sorry, i do what you said in first comment, pause and unpause player then audio back, there's maybe something with koe, not really know

thank you <3
