### ISSUE TITLE
playlist urls are not really working correctly.

### ISSUE THREAD

**Issue by Tomato6966** [Walkyst/lavaplayer-fork#62]
The url:
https://music.youtube.com/playlist/?list=PLhlYlDBoaODZh7oYlcARKFvFiocV5DOeZ 

does **NOT** Work

but
https://music.youtube.com/playlist?list=PLhlYlDBoaODZh7oYlcARKFvFiocV5DOeZ

**DOES**

what is different?

the / after playlist -> it's still valid, as if you visit the page it's valid.

maybe there are more cases like that

this should be working due to url formatting 

like if you enter it with `playlist/?list=` the browser formats it to `playlist?list=`

should be easy to fix.

**Comment by Walkyst** [comment]
Does YouTube gives you this wrong URL?
