### ISSUE TITLE
Where does connector.so come from?

### ISSUE THREAD

**Issue by MrSmoer** [Walkyst/lavaplayer-fork#69]
I run lavaplayer on a Raspberry Pi, but some videos did not play.
I narrowed it down to the fact that I am missing libconnector.so

I found various more or less suspicious download links it, so I just wanted to ask where I can obtain one/where the source-code is to compile it myself.

Thank you!

**Comment by holasoyender** [comment]
You are probably looking for https://github.com/Walkyst/lavaplayer-natives-fork

**Comment by MrSmoer** [comment]
Thank you! I don't know how I overlooked that, thank you!
