### ISSUE TITLE
Bug with client screen EMBED

### ISSUE THREAD

**Issue by DolbyDev** [Walkyst/lavaplayer-fork#7]
while the video does not enable embed it's showing "Playback on other websites has been disabled by the video owner."
video testing `zHqS3bS4fpk`

**Comment by Walkyst** [comment]
Okay, youtube is annoying, i just did commit with random youtube account for avoiding age restrictions and removed embed screen parameter

**Comment by DolbyDev** [comment]
> Okay, youtube is annoying, i just did commit with random youtube account for avoiding age restrictions and removed embed screen parameter, but anyway i recommend use your own account, because current default can stop working at any time

 Cookies are not long-lived and can be broken at any time for a specific reason. I prefer to add two requests: the first request with `clientScreen` and the second request without `clientScreen`, the second request is used if the reason is `Playback on other websites has been disabled by the video owner.`, what do you think?

**Comment by Walkyst** [comment]
I'm using my cookie since june without changing it, everything is good and if video age-gated and with disabled embed it can be played only with auth cookie
