### ISSUE TITLE
MP3 trys to access TMP folder.

### ISSUE THREAD

**Issue by DxsSucuk** [Walkyst/lavaplayer-fork#77]
While using the Library with MP3 files it will try accessing the TMP folder on linux, and if you have a limit user this does not work.
I personally would recommend creating a tmp folder in the current directory.

This is an Issue by Lavaplayer itself and by the fork.

**Comment by topi314** [comment]
`/tmp` is available for all users on your system no matter what(`drwxrwxrwt`).

The issue that you are seeing here is 2 different users trying to write to `/tmp/lava-jni-natives` as that sub-folder is created with `drwxr-xr-x`.

Just run your different bots with the same user and there will be no issue at all. (You might need to manually delete `/tmp/ava-jni-natives` before it starts working again ofc)

**Comment by DxsSucuk** [comment]
The Issue is that I am using Jetbrains Gateway to run it remotly on my server while still working on it, and for security reasons the user is quite limited. So basically I could just change the folder permission and it should work?

**Comment by topi314** [comment]
You would have to change the permissions of `/tmp/lava-jni-natives` on every startup
The saver bet would be to just override the java tmp directory I think
`java -Djava.io.tmpdir=/tmp/some_folder`

Like this every bot should write to its own subfolder in `/tmp`

**Comment by DxsSucuk** [comment]
Thats exactly what I needed thanks!
