### ISSUE TITLE
[Feature-Req/Bug] Lavaplayer 410 / Age Restricted

### ISSUE THREAD

**Issue by thxrben** [Walkyst/lavaplayer-fork#82]
Lavaplayer can - once again - not play age-restricted videos.
I havent heard of any discussion, and since the last issue here is from oct 2022 in regards to this, I will open a new issue.

The Player (when printing the Stack-Trace) says:

Something broke when playing the track
...
Error when extracting from EID: xxx-xxx-xxx-xxx-xxx, mainJson <redacted>
...
Invalid status code for video info response: 410

I can only assume this is due to age-restricted content.

Now, I dont know anything about the YT-API, but would it be possible to share cookies / let lavaplayer login with a Account that can be used to play the videos?

**Comment by Walkyst** [comment]
What version you use?

**Comment by thxrben** [comment]
I just made sure i was using 1.3.99-2, but now i get a different error. Its about org.json.JSONObject.toMap() which is not defined. I assume I am missing some library. I gotta check before continuing this.

**Comment by thxrben** [comment]
Sorry.
I had still the old lava-player library after changing the dependency to this fork.
Now i got it updated and it seems to work for now. 
From this view, this issue can be closed.

Still, In case youtube enforces the age-restrictions harder, would providing an API-Key / AuthCookie / Login via a YT-Account be an option? Haven't seen anyone try this yet.

**Comment by Walkyst** [comment]
You can pass login and password into youtube source manager constructor

**Comment by thxrben** [comment]
Good to know.
Thank you very much!
