### ISSUE TITLE
Fork for private use

### ISSUE THREAD

**Issue by RedHeadEmile** [Walkyst/lavaplayer-fork#88]
Hi, I'm using your fork for personnal use and I created a fork to use your custom branch as main branch and being able to import it with Jitpack.io. Are you okay with that ?
Otherwise, is it possible for you to publish release of your custom version ?

Thanks in advance for you answer.
Best regards

**Comment by topi314** [comment]
You can already perfectly fine import the custom branch via jitpack

That's what everyone here is doing

**Comment by RedHeadEmile** [comment]
Alright, I didn't know you can import branches with jitpack.
Maybe it would be nice to add it in the README.

`implementation 'com.github.walkyst.lavaplayer-fork:lavaplayer:custom-SNAPSHOT'`

**Comment by topi314** [comment]
Instead of using branches you should be using the short commit hash to guarantee reproducible builds
