### ISSUE TITLE
Load exception on lavaplayer 1.4.0

### ISSUE THREAD

**Issue by aikaterna** [Walkyst/lavaplayer-fork#94]
I don't use Lavaplayer directly as I use Lavalink as you will see from the logs, but wanted to report this issue.

Using latest Lavalink 3.7.5 with Lavaplayer 1.4.0-original, this message has appeared for one specific url that I've seen so far:
`com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video can only be played on newer versions of Android or other supported devices.`

https://gist.githubusercontent.com/aikaterna/d3a03bb46202a6c44e793d61ae062cde/raw/f7a6d061e29a3edf3aedaad71116218936b14549/lp140-exception

**Comment by aikaterna** [comment]
A user informed me "Looks like `YouTube Movies & TV` videos cause the issue".

**Comment by Walkyst** [comment]
This video available only in US so unfortunately I can't test and fix this

**Comment by tehbasshunter** [comment]
I'm the person who happened to initially discover the issue with the aforementioned channel. 👋🏼 

With the exception of a couple videos that happened to be available in Canada and Australia in addition to the US it seems that all of their "videos" are Geoblocked outside of the US entirely making it a tad difficult to fix this.
